[server]
enableStaticServing = true
headless = true  # force headless mode on Cloud

[browser]
gatherUsageStats = false  # disable onboarding/email prompt

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"
